name: github-pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  debug-linux-x86_64:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: debug-linux-x86_64
        run: |
          sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y  # Install OS updates.
          rustc --version && cargo --version  # Display rustc and cargo versions.
          RUST_BACKTRACE=full cargo build --verbose
          mkdir -p rust-playground-api/rust-playground-api
          cp target/debug/main rust-playground-api/rust-playground-api/rust-playground-api
          chmod 755 rust-playground-api/rust-playground-api/rust-playground-api

      - name: rust-playground-api-debug-linux-x86_64
        uses: actions/upload-artifact@v2
        with:
          name: rust-playground-api-debug-linux-x86_64
          path: |
            rust-playground-api

  release-linux-x86_64:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: release-linux-x86_64
        run: |
          sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y  # Install OS updates.
          rustc --version && cargo --version  # Display rustc and cargo versions.
          RUST_BACKTRACE=full cargo build --release --verbose
          mkdir -p rust-playground-api/rust-playground-api
          cp target/release/main rust-playground-api/rust-playground-api/rust-playground-api
          strip -s rust-playground-api/rust-playground-api/rust-playground-api
          chmod 755 rust-playground-api/rust-playground-api/rust-playground-api

      - name: rust-playground-api-release-linux-x86_64
        uses: actions/upload-artifact@v2
        with:
          name: rust-playground-api-release-linux-x86_64
          path: |
            rust-playground-api
